import type { Metadata } from "next";
import { Poppins, Roboto, Barlow_Condensed, Outfit } from "next/font/google";

import { Providers, Header, Footer, ScrollToTop } from "@/components/layout";

import "@/styles/reset.css";
import "@/styles/variables.css";
import "@/styles/global.css";

import styles from "./layout.module.css";

const poppins = Poppins({
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-poppins",
  subsets: ["latin"],
});

const roboto = Roboto({
  weight: ["300", "400", "500", "700"],
  variable: "--font-roboto",
  subsets: ["latin"],
});

const outfit = Outfit({
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-outfit",
  subsets: ["latin"],
});

const barlowCondensed = Barlow_Condensed({
  weight: ["600"],
  variable: "--font-barlow",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${poppins.variable} ${roboto.variable} ${barlowCondensed.variable} ${outfit.variable}`}
    >
      <body>
        <Providers>
          <div className={styles.layout}>
            <ScrollToTop />
            <Header />
            <div className={styles.contentWrapper}>{children}</div>
            <Footer />
          </div>
        </Providers>
      </body>
    </html>
  );
}
